name: Renovate
services:
  Renovate:
    image: renovate/renovate:43.83@sha256:956dc81186c8a02fc1cbaf803fe884f619434116566443b5d1a18ae8738f7759
    container_name: Renovate
    restart: no
    hostname: renovate
    networks:
      Renovate:
    volumes:
      - Renovate:/tmp/renovate/cache
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://${GITEA_HOSTNAME}/api/v1
      RENOVATE_TOKEN: ${GITEA_TOKEN}
      RENOVATE_AUTODISCOVER: true
      RENOVATE_AUTODISCOVER_FILTER: ${GITEA_ORG}/*
      RENOVATE_ONBOARDING_CONFIG: '{"extends": ["local>${GITEA_ORG}/renovate-config"]}'
      RENOVATE_GITHUB_COM_TOKEN: ${GITHUB_TOKEN}

networks:
  Renovate:
    external: true

volumes:
  Renovate:
