name: Renovate
services:
  Renovate:
    image: renovate/renovate:44.39@sha256:27f008cc48b952dff1fdceed42ef91f243f31e64596dc7f5a8754467961243ad
    container_name: Renovate
    restart: no
    hostname: renovate
    networks:
      Renovate:
    volumes:
      - renovate_cache:/tmp/renovate/cache
      - renovate_repos:/tmp/renovate/repos
    environment:
      RENOVATE_PLATFORM: forgejo
      RENOVATE_ENDPOINT: https://${GIT_SERVER_HOSTNAME}/api/v1
      RENOVATE_TOKEN: ${GIT_SERVER_TOKEN}
      RENOVATE_AUTODISCOVER: true
      RENOVATE_AUTODISCOVER_FILTER: ${GIT_REPO:-${GIT_SERVER_ORG}/*}
      RENOVATE_ONBOARDING_CONFIG: '{"extends": ["local>${GIT_SERVER_ORG}/renovate-config"]}'
      RENOVATE_GITHUB_COM_TOKEN: ${GITHUB_TOKEN}

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

    logging:
      driver: journald

    deploy:
      resources:
        limits:
          cpus: 1.5
          memory: 2GB
          pids: 50

networks:
  Renovate:
    external: true

volumes:
  renovate_cache:
  renovate_repos:
