name: Renovate
services:
  Renovate:
    image: renovate/renovate:43.88@sha256:39a559aeb62535cbfe40d8a4b30f4557ba3fa274526c0fd004142df86c5fb6bf
    container_name: Renovate
    restart: no
    hostname: renovate
    networks:
      Renovate:
    volumes:
      - Renovate:/tmp/renovate/cache
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://${GITEA_HOSTNAME}/api/v1
      RENOVATE_TOKEN: ${GITEA_TOKEN}
      RENOVATE_AUTODISCOVER: true
      RENOVATE_AUTODISCOVER_FILTER: ${GIT_REPO:-${GITEA_ORG}/*}
      RENOVATE_ONBOARDING_CONFIG: '{"extends": ["local>${GITEA_ORG}/renovate-config"]}'
      RENOVATE_GITHUB_COM_TOKEN: ${GITHUB_TOKEN}

networks:
  Renovate:
    external: true

volumes:
  Renovate:
